In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("/content/customer_shopping_behavior.csv")
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [ ]:
# Which product category has the most purchases?
df['Category'].value_counts()

Category
Clothing       1737
Accessories    1240
Footwear        599
Outerwear       324
Name: count, dtype: int64

In [ ]:
# Which category has the highest total purchase amount?
df.groupby('Category')['Purchase Amount (USD)'].sum().sort_values(ascending=False)

Category
Clothing       104264
Accessories     74200
Footwear        36093
Outerwear       18524
Name: Purchase Amount (USD), dtype: int64

In [ ]:
# Which season generates the highest sales?
highest_sales = df.groupby('Season')['Purchase Amount (USD)'].sum().sort_values(ascending=False)
highest_sales

Season
Fall      60018
Spring    58679
Winter    58607
Summer    55777
Name: Purchase Amount (USD), dtype: int64

In [ ]:
# Which gender has a higher average purchase amount?
gender_analysis = df.groupby("Gender")["Purchase Amount (USD)"].mean().sort_values(ascending=False)
gender_analysis

Gender
Female    60.249199
Male      59.536199
Name: Purchase Amount (USD), dtype: float64

In [ ]:
# Which product categories receive the highest customer ratings
rating = df.groupby("Category")["Review Rating"].mean().sort_values(ascending=False)
rating

Category
Footwear       3.793771
Accessories    3.769976
Outerwear      3.745652
Clothing       3.721537
Name: Review Rating, dtype: float64

In [ ]:
# Which products generate the highest total purchase amount?
product_sales = (
    df.groupby("Item Purchased")["Purchase Amount (USD)"]
    .sum()
    .sort_values(ascending=False)
)
product_sales

Item Purchased
Blouse        10410
Shirt         10332
Dress         10320
Pants         10090
Jewelry       10010
Sunglasses     9649
Belt           9635
Scarf          9561
Sweater        9462
Shorts         9433
Skirt          9402
Hat            9375
Coat           9275
Socks          9252
Jacket         9249
T-shirt        9248
Shoes          9240
Sandals        9200
Boots          9018
Handbag        8857
Hoodie         8767
Backpack       8636
Sneakers       8635
Gloves         8477
Jeans          7548
Name: Purchase Amount (USD), dtype: int64

In [ ]:
# Which purchase frequency has the highest average purchase amount?
purchase_frequency = df.groupby("Frequency of Purchases")["Purchase Amount (USD)"].mean()
purchase_frequency

Frequency of Purchases
Annually          60.173077
Bi-Weekly         60.694698
Every 3 Months    60.082192
Fortnightly       59.053506
Monthly           59.330922
Quarterly         59.984014
Weekly            58.972171
Name: Purchase Amount (USD), dtype: float64

In [ ]:
# Creating the age groups colunm
df['Age Group'] = pd.cut(
    df['Age'],
    bins=[0, 18, 25, 35, 45, 55, 100],
    labels=['Under 18', '18–25', '26–35', '36–45', '46–55', 'Above 55']
)
df

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases,Age Group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,46–55
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,18–25
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,46–55
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,18–25
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,36–45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3895,3896,40,Female,Hoodie,Clothing,28,Virginia,L,Turquoise,Summer,4.2,No,2-Day Shipping,No,No,32,Venmo,Weekly,36–45
3896,3897,52,Female,Backpack,Accessories,49,Iowa,L,White,Spring,4.5,No,Store Pickup,No,No,41,Bank Transfer,Bi-Weekly,46–55
3897,3898,46,Female,Belt,Accessories,33,New Jersey,L,Green,Spring,2.9,No,Standard,No,No,24,Venmo,Quarterly,46–55
3898,3899,44,Female,Shoes,Footwear,77,Minnesota,S,Brown,Summer,3.8,No,Express,No,No,24,Venmo,Weekly,36–45
3899,3900,52,Female,Handbag,Accessories,81,California,M,Beige,Spring,3.1,No,Store Pickup,No,No,33,Venmo,Quarterly,46–55

In [ ]:
# Which age group has the highest number of customers?
age_group = df['Age Group'].value_counts().sort_values(ascending=False)
age_group

Age Group
Above 55    1105
46–55        753
26–35        742
36–45        729
18–25        502
Under 18      69
Name: count, dtype: int64

In [6]:
# Does a higher previous purchase count correspond to higher customer spending?
df.groupby('Previous Purchases')['Purchase Amount (USD)'].mean()

Previous Purchases
1     58.469880
2     60.333333
3     58.560440
4     61.274725
5     64.252874
6     55.850575
7     61.200000
8     66.671642
9     63.784615
10    58.184211
11    59.500000
12    59.253165
13    55.884058
14    57.967391
15    55.863014
16    62.157143
17    61.462687
18    59.142857
19    57.474359
20    61.891566
21    57.979167
22    54.753846
23    57.904110
24    60.197802
25    61.278481
26    58.870130
27    57.756410
28    61.887500
29    59.739130
30    59.353659
31    57.288660
32    61.530864
33    61.987805
34    54.050633
35    59.269841
36    62.239437
37    60.512821
38    65.142857
39    57.061728
40    54.207317
41    60.757143
42    58.855422
43    61.687500
44    61.291667
45    57.566265
46    59.589744
47    62.655556
48    63.588889
49    56.500000
50    65.272727
Name: Purchase Amount (USD), dtype: float64

In [9]:
# Which products are purchased most frequently?
top_products = df["Item Purchased"].value_counts().head(10)
top_products

Item Purchased
Blouse        171
Pants         171
Jewelry       171
Shirt         169
Dress         166
Sweater       164
Jacket        163
Coat          161
Sunglasses    161
Belt          161
Name: count, dtype: int64